# test-theme-detect.ps1 — verify theme detection matches system setting
$ErrorActionPreference = 'Stop'
$base = (Get-Item (Split-Path $MyInvocation.MyCommand.Path)).Parent.Parent.FullName

Write-Host "=== Test 12: Theme Detection ===" -ForegroundColor Cyan

# Read current system theme
$regPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"
try {
    $sysLight = (Get-ItemProperty -Path $regPath -Name "SystemUsesLightTheme" -ErrorAction Stop).SystemUsesLightTheme
    Write-Host "System registry: SystemUsesLightTheme = $sysLight"
} catch {
    Write-Host "FAIL: Cannot read registry at $regPath" -ForegroundColor Red
    exit 1
}

# Launch dock and check theme from debug output
$exe = "$base\WinDock-d.exe"
if (-not (Test-Path $exe)) {
    Write-Host "FAIL: $exe not found" -ForegroundColor Red
    exit 1
}

$iconDbg = "C:\temp\_icon_debug.txt"
if (Test-Path $iconDbg) { Remove-Item $iconDbg -Force }

Write-Host "Launching WinDock-d.exe --debug..."
$proc = Start-Process $exe -ArgumentList '--debug' -PassThru
Start-Sleep 4

# Check if the dock picked up the correct theme
# The Theme event is logged to _icon_debug.txt
if (Test-Path $iconDbg) {
    $dbgContent = Get-Content $iconDbg -Raw
    Write-Host "Debug output:"
    $dbgContent -split "`n" | Select-Object -First 5 | ForEach-Object { Write-Host "  $_" }

    # Look for IsLight mentions
    if ($dbgContent -match 'IsLight=(True|False)') {
        $matched = $Matches[1]
        $dockLight = $matched -eq 'True'
        Write-Host "Dock detected theme: IsLight=$dockLight"
        if ($dockLight -eq ($sysLight -eq 1)) {
            Write-Host "  PASS: Dock theme matches system setting" -ForegroundColor Green
        } else {
            Write-Host "  FAIL: Dock theme ($dockLight) != system ($($sysLight -eq 1))" -ForegroundColor Red
        }
    } else {
        Write-Host "  INFO: No explicit IsLight in debug output, checking startup log..."
    }
} else {
    Write-Host "  INFO: _icon_debug.txt not found — theme may not be logged there"
}

# Alternative: check _dock_startup.txt for theme info
$startupLog = "C:\temp\_dock_startup.txt"
if (Test-Path $startupLog) {
    $startupContent = Get-Content $startupLog -Raw
    Write-Host "Startup log:"
    Write-Host "  $startupContent"
}

# Verify theme files exist (GlassBmp is generated by Theme.Init)
# We can't directly inspect in-process objects, but the dock not crashing
# and creating debug output means Theme.Init() completed successfully.
if ($proc -and !$proc.HasExited) {
    Write-Host "  PASS: Dock running after Theme.Init() — no crash" -ForegroundColor Green
} else {
    Write-Host "  FAIL: Dock crashed during Theme.Init()" -ForegroundColor Red
}

# Cleanup
if ($proc -and !$proc.HasExited) { $proc.Kill(); $proc.WaitForExit(2000) }

# Test: toggle registry theme and see if dock updates
Write-Host "Testing live theme update..."
$originalValue = $sysLight
$newValue = if ($originalValue -eq 1) { 0 } else { 1 }

try {
    Set-ItemProperty -Path $regPath -Name "SystemUsesLightTheme" -Value $newValue
    Write-Host "  Set SystemUsesLightTheme to $newValue"

    # Launch dock again — it should pick up new theme
    if (Test-Path $iconDbg) { Remove-Item $iconDbg -Force }
    $proc2 = Start-Process $exe -ArgumentList '--debug' -PassThru
    Start-Sleep 4

    if ($proc2 -and !$proc2.HasExited) {
        Write-Host "  PASS: Dock launched with changed theme — no crash" -ForegroundColor Green
    }

    if ($proc2 -and !$proc2.HasExited) { $proc2.Kill(); $proc2.WaitForExit(2000) }
} finally {
    # Restore original
    Set-ItemProperty -Path $regPath -Name "SystemUsesLightTheme" -Value $originalValue
    Write-Host "  Restored SystemUsesLightTheme to $originalValue"
}

Write-Host "RESULT: PASS" -ForegroundColor Green
exit 0
